---
- name: Create zookeeper_tar directory
  hosts: servers
  become: yes
  vars_files:
    - /data/work/zookeeper_3.7.2_ansible/main.yml
  tasks:
    - name: Create zookeeper_tar directory
      file:
        path: "{{ zoo_tar_path }}"
        state: directory

    - name: Create work directory
      file:
        path: "{{ work_dir }}"
        state: directory


- name: Copy zookeeper_tar to servers
  hosts: localhost
  become: yes
  vars_files:
    - /data/work/zookeeper_3.7.2_ansible/main.yml
  tasks:
    - name: tar_scp.sh Start
      shell: "{{ play_book_dir }}/tar_scp.sh {{ play_book_dir }} {{ zoo_tar_path }}"


- name: Extract zookeeper_tar
  hosts: servers
  become: yes
  vars_files:
    - /data/work/zookeeper_3.7.2_ansible/main.yml
  tasks:
    - name: Extract the zookeeper tarball
      unarchive:
        src: "{{ zoo_tar_path }}/{{ zoo_tar_filename }}"
        dest: "{{ work_dir }}"
        remote_src: yes


- name: sb_link
  hosts: servers
  become: yes
  vars_files:
    - /data/work/zookeeper_3.7.2_ansible/main.yml
  tasks:
    - name: Spark link gogo
      shell: "ln -s {{ work_dir }}/*zookeeper-?.?.?-* {{ work_dir }}/zookeeper"
      args:
        creates: "{{ work_dir }}/zookeeper"


- name: entrypoint_sh start
  hosts: localhost
  become: yes
  vars_files:
    - /data/work/zookeeper_3.7.2_ansible/main.yml
  tasks:
    - name: entry_point_sh start
      shell: "{{ play_book_dir }}/entrypoint.sh {{work_dir}}"


- name: zookeeper run
  hosts: servers
  become: yes
  vars_files:
    - /data/work/zookeeper_3.7.2_ansible/main.yml
  tasks:
    - name: zookeeper run
      shell: "{{ work_dir }}/zookeeper/bin/zkServer.sh start"
